build: off

environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.8
      MINICONDA: C:\Miniconda38-x64
      PYTHON_ARCH: "64"



init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - '"%MINICONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
#  - conda install --yes conda-build
  - conda config --add channels conda-forge
  - conda config --add channels https://conda.anaconda.org/qttesting
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy algopy pytest pytest-runner pytest-pep8 pytest-cov matplotlib pyqt pip statsmodels line_profiler IPython"

  - activate test-environment
  - "python -m pip install --upgrade pip"
  - "python -m pip install --upgrade setuptools"
  - "python -m pip install --upgrade pytest"
  - pip install coverage
  - pip install hypothesis
  - python setup.py install
#  - python setup.py sdist
#  - pip install numdifftools --find-links=dist

test_script:
  # - coverage run --source=numdifftools setup.py test
  - coverage run --source=numdifftools -m py.test build/lib


after_test:
  # If tests are successful, create binary packages for the project.
  # - python setup.py bdist_wheel"
  # - python setup.py bdist_wininst"
  # - python setup.py bdist_msi"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
